validpairs="${1}"
output_dir="${2}"

#chr=("chr1" "chr2" "chr3" "chr4" "chr5" "chr6" "chr7" "chr8" "chr9" "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18" "chr19" "chr20" "chr21" "chr22" "chrX")
#for i in "${chr[@]}"
#do
#	a="${i}"
#	awk '{if($2 == a && $8 == a ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${i}"
#done

chr="chr1"
awk '{if($2 == "chr1" && $8 == "chr1" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr2"
awk '{if($2 == "chr2" && $8 == "chr2" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr3"
awk '{if($2 == "chr3" && $8 == "chr3" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr4"
awk '{if($2 == "chr4" && $8 == "chr4" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr5"
awk '{if($2 == "chr5" && $8 == "chr5" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr6"
awk '{if($2 == "chr6" && $8 == "chr6" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr7"
awk '{if($2 == "chr7" && $8 == "chr7" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr8"
awk '{if($2 == "chr8" && $8 == "chr8" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr9"
awk '{if($2 == "chr9" && $8 == "chr9" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr10"
awk '{if($2 == "chr10" && $8 == "chr10" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"

chr="chr11"
awk '{if($2 == "chr11" && $8 == "chr11" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr12"
awk '{if($2 == "chr12" && $8 == "chr12" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr13"
awk '{if($2 == "chr13" && $8 == "chr13" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr14"
awk '{if($2 == "chr14" && $8 == "chr14" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr15"
awk '{if($2 == "chr15" && $8 == "chr15" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr16"
awk '{if($2 == "chr16" && $8 == "chr16" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr17"
awk '{if($2 == "chr17" && $8 == "chr17" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr18"
awk '{if($2 == "chr18" && $8 == "chr18" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr19"
awk '{if($2 == "chr19" && $8 == "chr19" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr20"
awk '{if($2 == "chr20" && $8 == "chr20" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"

chr="chr21"
awk '{if($2 == "chr21" && $8 == "chr21" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chr22"
awk '{if($2 == "chr22" && $8 == "chr22" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"
chr="chrX"
awk '{if($2 == "chrX" && $8 == "chrX" ){print $3"\t"$9}}' "${validpairs}" > "${output_dir} ${chr}"



